version: "3.9"

services:
  adminer:  #Dung de quan ly database
    image: adminer:latest
    container_name: adminer  #Ten container
    restart: always
    ports:
      - "5050:8080"
    depends_on:
      - postgres
    networks:
      - spring-network
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring-network

  app:
    build: .
    container_name: springboot_app
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      #Support more environment variables here.
      ACCESS_SECRET: 121c654d-3dc7-496e-b4af-9d31b27b3002
      REFRESH_SECRET: 7f9ca4c4-6fae-4982-ae67-8b58eaf3af81
      RESET_PASSWORD_SECRET: 1b3e891d-289b-4d6c-acca-413927956efa
      VERIFY_EMAIL_SECRET: 981d5f23-dbf9-4d0e-99c7-b927eb1a7719
    networks:
      - spring-network

volumes:
  postgres_data:

networks:
  spring-network: