spring.config.import=optional:file:.env[.properties]
spring.application.name=JobPortal
spring.jackson.default-property-inclusion=non_null
#https://www.baeldung.com/springboot-jpa-automatically-create-database-schema
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
#spring.datasource.url=jdbc:postgresql://ep-green-hall-a112s5b6-pooler.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
#spring.datasource.username=neondb_owner
#spring.datasource.password=npg_0UrdS2pEaBlh
spring.datasource.driver-class-name=org.postgresql.Driver
#create if want to drop table, updtae if want to keep the able
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#Spring prefix version 2 (for New version)
server.servlet.contextPath=/api
#Api documentation
#//Custom path, default is scalar
scalar.enabled=${APP_API_DOCS}
scalar.path=/docs

#Custom environment
app.environment=${APP_ENVIRONMENT}
app.frontend.url=${FRONTEND_URL}
app.secret.reset.password=${RESET_PASSWORD_SECRET}
app.secret.verify.email=${VERIFY_EMAIL_SECRET}
app.secret.access=${ACCESS_SECRET}
app.secret.refresh=${REFRESH_SECRET}
server.port=${SERVER_PORT:8080}
minio.url=${MINIO_URL}
minio.access.name=${MINIO_ACCESS_NAME}
minio.access.secret=${MINIO_ACCESS_SECRET}
minio.bucket.name=${MINIO_BUCKET_NAME}