spring.application.name=JobPortal
spring.jackson.default-property-inclusion=non_null
#https://www.baeldung.com/springboot-jpa-automatically-create-database-schema
spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=admin
spring.datasource.password=admin
#spring.datasource.url=jdbc:postgresql://ep-green-hall-a112s5b6-pooler.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
#spring.datasource.username=neondb_owner
#spring.datasource.password=npg_0UrdS2pEaBlh
spring.datasource.driver-class-name=org.postgresql.Driver
#create if want to drop table, updtae if want to keep the able
spring.jpa.hibernate.ddl-auto=create 
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#Spring prefix version 2 (for New version)
server.servlet.contextPath=/api
#Api documentation
#//Custom path, default is scalar
scalar.enabled=true
scalar.path=/docs

#Custom environment
app.frontend.url=http://localhost:5173 
app.secret.reset.password=b1875963-d606-4ae1-a216-dc31d4981042
app.secret.verify.email=1e71567b-8e0e-40fb-96e4-443ec9637192
app.secret.access=274a2e6c-d345-4f9d-9fd7-b956b7ffa38d
app.secret.refresh=39e8b8b5-8667-4c4a-abc6-18da850282e4
server.port=8080
minio.url=http://localhost:9000
minio.access.name=minioadmin
minio.access.secret=minioadmin
minio.bucket.name=jobportal