spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/mydb
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

minio:
  endpoint: http://minio:9000
  url: http://localhost:9000
  access:
    name: minioadmin
    secret: minioadmin
  bucket:
    name: jobportal

app:
  secret:
    access: change-me-access-secret
    refresh: change-me-refresh-secret
    reset:
      password: change-me-reset-password-secret
    verify:
      email: change-me-verify-email-secret
