spring.application.name=JobPortal
spring.jackson.default-property-inclusion=non_null
#https://www.baeldung.com/springboot-jpa-automatically-create-database-schema
spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=admin
spring.datasource.password=admin
#spring.datasource.url=jdbc:postgresql://ep-green-hall-a112s5b6-pooler.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
#spring.datasource.username=neondb_owner
#spring.datasource.password=npg_0UrdS2pEaBlh
spring.datasource.driver-class-name=org.postgresql.Driver
#create if want to drop table
spring.jpa.hibernate.ddl-auto=create  
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#Spring prefix version 2 (for New version)
server.servlet.contextPath=/api
#Api documentation
#//Custom path, default is scalar
scalar.enabled=true
scalar.path=/docs

#Custom environment
app.frontend.url=http://localhost:5173 
app.secret.reset.password=${RESET_PASSWORD_SECRET}
app.secret.verify.email=${VERIFY_EMAIL_SECRET}
app.secret.access=${ACCESS_SECRET}
app.secret.refresh=${REFRESH_SECRET}